# Generated by Django 3.2.8 on 2021-10-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('pin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('product_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('product_price', models.IntegerField(default=0)),
                ('product_img', models.FileField(upload_to='')),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('product_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('product_price', models.IntegerField(default=0)),
                ('product_img', models.FileField(upload_to='')),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('product_desc', models.CharField(max_length=500, null=True)),
                ('product_price', models.IntegerField(default=0)),
                ('product_img', models.FileField(upload_to='')),
                ('product_img2', models.FileField(null=True, upload_to='')),
                ('product_img3', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
